package tw.com.chanping

class st_goods {
	String ctmno
	String ctmname
	String shortname
	String tel1
	String tel2
	String fax1
	String fax2
	String mobtel
	String email
	String addresss
	String addresss2
	String addresss3
	String addressc
	String addressr
	String attention
	String attention2
	String attention3
	String attention4
	String attention5
	String attention6
	String attention7
	String attention8
	String attention9
	String attention1
	String president
	String payment
	BigDecimal paytype
	BigDecimal payday
	String idno
	BigDecimal debtday
	BigDecimal credit
	BigDecimal usecredit
	BigDecimal debt
	String rem
	BigDecimal initdebt
	BigDecimal discrate
	String areano
	String salesno
	BigDecimal outside
	String placeno
	Date datadate
	String kindno
	BigDecimal ctmkindno
	String ectmname
	String abbrname
	String contact1
	String contact2
	String contact3
	String sendtel1
	String sendtel2
	String sendtel3
	String addr1
	String addr2
	String addr3
	String addr4
	BigDecimal basevalue
	Date startdate
	String curtype
	String tbkname
	String taccount
	String cur_p
	BigDecimal prepay
	String dts
	String website
	String gradeno
	String markno
	String comeinno
	BigDecimal okrate
	String countryno
	String seqno
	String atel2
	String atel3
	String atel4
	String atel5
	String atel6
	String atel7
	String atel8
	String atel9
	String atel10
	String aemail2
	String aemail3
	String aemail4
	String aemail5
	String aemail6
	String aemail7
	String aemail8
	String aemail9
	String aemail10
	BigDecimal taxmark
	BigDecimal ctmtype
	Date birthdate
	BigDecimal sex
	Date enddate
	BigDecimal smark
	String srem
	String cidno
	BigDecimal tax
	String ctmkname
	String udcname1
	String udcname2
	String udcname3
	String udcname4
	String udcname5
	String photo01
	String photo02
	String photo03
	String photo04
	String ctmnote
	String ctmnamer
	String ctmnamer2
	String ctmnamer3
	String ctmidno
	String ctmidno2
	String ctmidno3
	String sender
	String deptno
	BigDecimal paymday
	BigDecimal tax3in
	String paytrem
	String salesno2
	String deptno2
	String dtgno
	String ctmno2
	String ctmname2
	String sysfld01
	String sysfld02
	String sysfld03
	String sysfld04
	BigDecimal blood
	BigDecimal marrymk
	String hobby
	String aceseundem
	String eundem
	String birthplace
	String qseqno
	BigDecimal pointqty
	String rctmno1
	String rctmno2
	BigDecimal csmark
	BigDecimal sex2
	BigDecimal sex3
	BigDecimal sex4
	BigDecimal sex5
	BigDecimal sex6
	BigDecimal sex7
	BigDecimal sex8
	BigDecimal sex9
	BigDecimal sex10
	Date birthdate2
	Date birthdate3
	Date birthdate4
	Date birthdate5
	Date birthdate6
	Date birthdate7
	Date birthdate8
	Date birthdate9
	Date birthdate1
	String pidno
	BigDecimal recpmk
	String tellist
	String crgradeno
	String crareano
	String crjobname
	String crcomeinno
	BigDecimal stopmk
	String membno
	String ckindno
	String cardno
	String addressc2
	String motel2
	Date indate
	Date atvdate
	BigDecimal chgmode
	String sbtime
	String setime
	String groupno
	Date chgdate
	String bmonth
	String emonth
	String creditno
	String crdfnum
	Date crddate
	Date bcrddate
	String bkaccno
	String crdtype
	String bkname
	String bkname2
	Date ecrddate
	String clamanter
	String clamtel
	String udfcap1
	String udfcap2
	String udfcap3
	String udfcap4
	String udfcap5
	String udfcap6
	String udfcap7
	String udfcap8
	String udfcap9
	String udfcap10
	String udfcap11
	String udfcap12
	String udfcap13
	String udfcap14
	String udfcap15
	String udfcap16
	String udfcap17
	String udfcap18
	String udfcap19
	String udfcap20
	String udffld1
	String udffld2
	String udffld3
	String udffld4
	String udffld5
	String udffld6
	String udffld7
	String udffld8
	String udffld9
	String udffld10
	String udffld11
	String udffld12
	String udffld13
	String udffld14
	String udffld15
	String udffld16
	String udffld17
	String udffld18
	String udffld19
	String udffld20
	String parentno
	String agnation
	BigDecimal datingno
	String cphoto
	BigDecimal incount
	String supno
	String paycon
	String webid
	String logno
	String logid
	BigDecimal passok

	static constraints = {
		ctmno nullable:true
		ctmname nullable:true
		shortname nullable:true
		tel1 nullable:true
		tel2 nullable:true
		fax1 nullable:true
		fax2 nullable:true
		mobtel nullable:true
		email nullable:true
		addresss nullable:true
		addresss2 nullable:true
		addresss3 nullable:true
		addressc nullable:true
		addressr nullable:true
		attention nullable:true
		attention2 nullable:true
		attention3 nullable:true
		attention4 nullable:true
		attention5 nullable:true
		attention6 nullable:true
		attention7 nullable:true
		attention8 nullable:true
		attention9 nullable:true
		attention1 nullable:true
		president nullable:true
		payment nullable:true
		paytype nullable:true
		payday nullable:true
		idno nullable:true
		debtday nullable:true
		credit nullable:true
		usecredit nullable:true
		debt nullable:true
		rem nullable:true
		initdebt nullable:true
		discrate nullable:true
		areano nullable:true
		salesno nullable:true
		outside nullable:true
		placeno nullable:true
		datadate nullable:true
		kindno nullable:true
		ctmkindno nullable:true
		ectmname nullable:true
		abbrname nullable:true
		contact1 nullable:true
		contact2 nullable:true
		contact3 nullable:true
		sendtel1 nullable:true
		sendtel2 nullable:true
		sendtel3 nullable:true
		addr1 nullable:true
		addr2 nullable:true
		addr3 nullable:true
		addr4 nullable:true
		basevalue nullable:true
		startdate nullable:true
		curtype nullable:true
		tbkname nullable:true
		taccount nullable:true
		cur_p nullable:true
		prepay nullable:true
		dts nullable:true
		website nullable:true
		gradeno nullable:true
		markno nullable:true
		comeinno nullable:true
		okrate nullable:true
		countryno nullable:true
		seqno nullable:true
		atel2 nullable:true
		atel3 nullable:true
		atel4 nullable:true
		atel5 nullable:true
		atel6 nullable:true
		atel7 nullable:true
		atel8 nullable:true
		atel9 nullable:true
		atel10 nullable:true
		aemail2 nullable:true
		aemail3 nullable:true
		aemail4 nullable:true
		aemail5 nullable:true
		aemail6 nullable:true
		aemail7 nullable:true
		aemail8 nullable:true
		aemail9 nullable:true
		aemail10 nullable:true
		taxmark nullable:true
		ctmtype nullable:true
		birthdate nullable:true
		sex nullable:true
		enddate nullable:true
		smark nullable:true
		srem nullable:true
		cidno nullable:true
		tax nullable:true
		ctmkname nullable:true
		udcname1 nullable:true
		udcname2 nullable:true
		udcname3 nullable:true
		udcname4 nullable:true
		udcname5 nullable:true
		photo01 nullable:true
		photo02 nullable:true
		photo03 nullable:true
		photo04 nullable:true
		ctmnote nullable:true
		ctmnamer nullable:true
		ctmnamer2 nullable:true
		ctmnamer3 nullable:true
		ctmidno nullable:true
		ctmidno2 nullable:true
		ctmidno3 nullable:true
		sender nullable:true
		deptno nullable:true
		paymday nullable:true
		tax3in nullable:true
		paytrem nullable:true
		salesno2 nullable:true
		deptno2 nullable:true
		dtgno nullable:true
		ctmno2 nullable:true
		ctmname2 nullable:true
		sysfld01 nullable:true
		sysfld02 nullable:true
		sysfld03 nullable:true
		sysfld04 nullable:true
		blood nullable:true
		marrymk nullable:true
		hobby nullable:true
		aceseundem nullable:true
		eundem nullable:true
		birthplace nullable:true
		qseqno nullable:true
		pointqty nullable:true
		rctmno1 nullable:true
		rctmno2 nullable:true
		csmark nullable:true
		sex2 nullable:true
		sex3 nullable:true
		sex4 nullable:true
		sex5 nullable:true
		sex6 nullable:true
		sex7 nullable:true
		sex8 nullable:true
		sex9 nullable:true
		sex10 nullable:true
		birthdate2 nullable:true
		birthdate3 nullable:true
		birthdate4 nullable:true
		birthdate5 nullable:true
		birthdate6 nullable:true
		birthdate7 nullable:true
		birthdate8 nullable:true
		birthdate9 nullable:true
		birthdate1 nullable:true
		pidno nullable:true
		recpmk nullable:true
		tellist nullable:true
		crgradeno nullable:true
		crareano nullable:true
		crjobname nullable:true
		crcomeinno nullable:true
		stopmk nullable:true
		membno nullable:true
		ckindno nullable:true
		cardno nullable:true
		addressc2 nullable:true
		motel2 nullable:true
		indate nullable:true
		atvdate nullable:true
		chgmode nullable:true
		sbtime nullable:true
		setime nullable:true
		groupno nullable:true
		chgdate nullable:true
		bmonth nullable:true
		emonth nullable:true
		creditno nullable:true
		crdfnum nullable:true
		crddate nullable:true
		bcrddate nullable:true
		bkaccno nullable:true
		crdtype nullable:true
		bkname nullable:true
		bkname2 nullable:true
		ecrddate nullable:true
		clamanter nullable:true
		clamtel nullable:true
		udfcap1 nullable:true
		udfcap2 nullable:true
		udfcap3 nullable:true
		udfcap4 nullable:true
		udfcap5 nullable:true
		udfcap6 nullable:true
		udfcap7 nullable:true
		udfcap8 nullable:true
		udfcap9 nullable:true
		udfcap10 nullable:true
		udfcap11 nullable:true
		udfcap12 nullable:true
		udfcap13 nullable:true
		udfcap14 nullable:true
		udfcap15 nullable:true
		udfcap16 nullable:true
		udfcap17 nullable:true
		udfcap18 nullable:true
		udfcap19 nullable:true
		udfcap20 nullable:true
		udffld1 nullable:true
		udffld2 nullable:true
		udffld3 nullable:true
		udffld4 nullable:true
		udffld5 nullable:true
		udffld6 nullable:true
		udffld7 nullable:true
		udffld8 nullable:true
		udffld9 nullable:true
		udffld10 nullable:true
		udffld11 nullable:true
		udffld12 nullable:true
		udffld13 nullable:true
		udffld14 nullable:true
		udffld15 nullable:true
		udffld16 nullable:true
		udffld17 nullable:true
		udffld18 nullable:true
		udffld19 nullable:true
		udffld20 nullable:true
		parentno nullable:true
		agnation nullable:true
		datingno nullable:true
		cphoto nullable:true
		incount nullable:true
		supno nullable:true
		paycon nullable:true
		webid nullable:true
		logno nullable:true
		logid nullable:true
		passok nullable:true
	}
}
