package tw.com.chanping

class st_opitem {
	String tradeno
	String salcno
	String ctmno
	BigDecimal line_no
	Date tradedate
	String goodno
	BigDecimal saleprice
	BigDecimal tradeqty
	BigDecimal cost
	BigDecimal discrate
	BigDecimal saleprice2
	BigDecimal pquan1
	BigDecimal pquan2
	BigDecimal pqty1
	BigDecimal pqty2
	BigDecimal pqty4
	String punit1
	String punit2
	String unit
	String rem
	BigDecimal osaleprice
	BigDecimal gcost
	BigDecimal smark
	String ctmgno
	String gmark
	BigDecimal exrate
	String curtype
	Date shipdate
	String recpno
	String goodno2
	String goodno3
	String rem1
	String gnote1
	String gnote2
	String gnote3
	String gnote4
	String gnote5
	String gnote15
	BigDecimal bommark
	BigDecimal pkno
	String lotno
	BigDecimal cobmk
	String okind
	BigDecimal gamount
	String dtgno
	String erpuser
	String prodno
	BigDecimal wtradeqty
	String wunit
	BigDecimal wsaleprice
	BigDecimal subqty
	BigDecimal wqtyscale
	BigDecimal sqtyscale
	String gcaccno
	BigDecimal btype
	BigDecimal btradeqty
	String rem2
	BigDecimal prtmark
	String goodname2
	BigDecimal bpkno
	BigDecimal sizemark
	BigDecimal omark
	BigDecimal pgmark
	String sizerem
	String orem
	String pgrem
	BigDecimal saddpri
	BigDecimal oaddpri
	BigDecimal paddpri
	String smemo
	String omemo
	String pmemo
	String tsmno
	BigDecimal tskno
	BigDecimal tsgno
	BigDecimal primark
	BigDecimal kbmark
	BigDecimal nosmark
	String note1
	String note2
	String note3
	BigDecimal wkmark
	BigDecimal wkprice
	BigDecimal wkqty
	String calfun
	Date inpdate
	BigDecimal hmark
	BigDecimal stax
	String tgitemno
	String tcolor
	String tsize
	BigDecimal taxrate
	String gtaxmark
	BigDecimal taxamt
	BigDecimal disprice
	BigDecimal colormk
	String sno

	static constraints = {
		tradeno nullable:true
		salcno nullable:true
		ctmno nullable:true
		line_no nullable:true
		tradedate nullable:true
		goodno nullable:true
		saleprice nullable:true
		tradeqty nullable:true
		cost nullable:true
		discrate nullable:true
		saleprice2 nullable:true
		pquan1 nullable:true
		pquan2 nullable:true
		pqty1 nullable:true
		pqty2 nullable:true
		pqty4 nullable:true
		punit1 nullable:true
		punit2 nullable:true
		unit nullable:true
		rem nullable:true
		osaleprice nullable:true
		gcost nullable:true
		smark nullable:true
		ctmgno nullable:true
		gmark nullable:true
		exrate nullable:true
		curtype nullable:true
		shipdate nullable:true
		recpno nullable:true
		goodno2 nullable:true
		goodno3 nullable:true
		rem1 nullable:true
		gnote1 nullable:true
		gnote2 nullable:true
		gnote3 nullable:true
		gnote4 nullable:true
		gnote5 nullable:true
		gnote15 nullable:true
		bommark nullable:true
		pkno nullable:true
		lotno nullable:true
		cobmk nullable:true
		okind nullable:true
		gamount nullable:true
		dtgno nullable:true
		erpuser nullable:true
		prodno nullable:true
		wtradeqty nullable:true
		wunit nullable:true
		wsaleprice nullable:true
		subqty nullable:true
		wqtyscale nullable:true
		sqtyscale nullable:true
		gcaccno nullable:true
		btype nullable:true
		btradeqty nullable:true
		rem2 nullable:true
		prtmark nullable:true
		goodname2 nullable:true
		bpkno nullable:true
		sizemark nullable:true
		omark nullable:true
		pgmark nullable:true
		sizerem nullable:true
		orem nullable:true
		pgrem nullable:true
		saddpri nullable:true
		oaddpri nullable:true
		paddpri nullable:true
		smemo nullable:true
		omemo nullable:true
		pmemo nullable:true
		tsmno nullable:true
		tskno nullable:true
		tsgno nullable:true
		primark nullable:true
		kbmark nullable:true
		nosmark nullable:true
		note1 nullable:true
		note2 nullable:true
		note3 nullable:true
		wkmark nullable:true
		wkprice nullable:true
		wkqty nullable:true
		calfun nullable:true
		inpdate nullable:true
		hmark nullable:true
		stax nullable:true
		tgitemno nullable:true
		tcolor nullable:true
		tsize nullable:true
		taxrate nullable:true
		gtaxmark nullable:true
		taxamt nullable:true
		disprice nullable:true
		colormk nullable:true
		sno nullable:true
	}
}
